config/routes.rb
Rails.application.routes.draw do
  resources :blogs do
    resources :posts, except: [:index] do
      resources :comments, except: [:index]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  root to: 'blogs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5 }
  has_many :posts, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :post, presence: true
  validates :content, presence: true
  validates :username, presence: true
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :blog, presence: true
  validates :content, presence: true
  validates :username, presence: true
  belongs_to :blog
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_blog
    @blog = Blog.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def blog_params
    params.require(:blog).permit(:title)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_blog
  before_action :load_post
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = @post.comments.build
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @post.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to [@blog, @post, @comment], notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: [@blog, @post, @comment] }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to [@blog, @post, @comment], notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: [@blog, @post, @comment] }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def load_blog
    @blog = Blog.find(params[:blog_id])
  end

  def load_post
    @post = @blog.posts.find(params[:post_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = @post.comments.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:username, :content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :load_blog
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts/1
  # GET /posts/1.json
  def show
    sleep 3
  end

  # GET /posts/new
  def new
    @post = @blog.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = @blog.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to [@blog, @post], notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: [@blog, @post] }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to [@blog, @post], notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: [@blog, @post] }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def load_blog
    @blog = Blog.find(params[:blog_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = @blog.posts.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:username, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def body_page_name
    @body_page_name ||= [controller_name.camelcase, action_name.camelcase].join
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/blogs/_form.html.slim
= form_for @blog do |f|
  - if @blog.errors.any?
    #error_explanation
      h2 = "#{pluralize(@blog.errors.count, "error")} prohibited this blog from being saved:"
      ul
        - @blog.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .actions = f.submit class: 'btn btn-primary'

app/views/blogs/edit.html.slim
h1 Editing blog

== render 'form'

= link_to 'Show', @blog, class: 'btn btn-secondary'
= link_to 'Back', blogs_path, class: 'btn btn-secondary'

app/views/blogs/index.html.slim
- content_for :head do
  meta name="position" content="blogs-list"

h1 Listing blogs


- @blogs.each do |blog|
  .row
    .col-sm-6
      ' Title:
      = blog.title
    .col-sm-6
      = link_to 'Show', blog, class: 'btn btn-secondary'
      = link_to 'Edit', edit_blog_path(blog), class: 'btn btn-secondary'
      = link_to 'Destroy', blog, class: 'btn btn-secondary', data: {:confirm => 'Are you sure?'}, :method => :delete

= link_to 'New Blog', new_blog_path, class: 'btn btn-primary'

app/views/blogs/new.html.slim
- content_for :head do
  meta name="position" content="blogs-new"
  meta name="added" content="new-tag"
  - @body_page_name = 'BlogsNew'
= javascript_include_tag 'blogs_new'

h1 New blog

== render 'form'

= link_to 'Back', blogs_path, class: 'btn btn-secondary'

app/views/blogs/show.html.slim
h1 = @blog.title

= link_to 'Edit', edit_blog_path(@blog), class: 'btn btn-primary'
= link_to 'Back', blogs_path, class: 'btn btn-secondary'

h4 Posts

- @blog.posts.each do |post|
  .row
    .col-xs-12
      = post.content
      ' by
      = post.username
    .col-sm-6
      = link_to 'Show', [@blog, post], class: 'btn btn-secondary'
      = link_to 'Edit', edit_blog_post_path(@blog, post), class: 'btn btn-secondary'
      = link_to 'Destroy', [@blog, post], class: 'btn btn-secondary', data: { :confirm => 'Are you sure?' }, :method => :delete

= link_to 'New Post', new_blog_post_path(@blog), class: 'btn btn-primary'

app/views/comments/_form.html.slim
= form_for [@blog, @post, @comment] do |f|
  - if @comment.errors.any?
    #error_explanation
      h2 = "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
      ul
        - @comment.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :username
    = f.text_field :username, class: 'form-control'
  .field
    = f.label :content
    = f.text_area :content, class: 'form-control'
  .actions = f.submit class: 'btn btn-primary'

app/views/comments/edit.html.slim
h1 Editing comment

== render 'form'

= link_to 'Show', [@blog, @post, @comment], class: 'btn btn-secondary'
= link_to 'Back', [@blog, @post], class: 'btn btn-secondary'

app/views/comments/new.html.slim
h1 New comment

== render 'form'

= link_to 'Back', [@blog, @post], class: 'btn btn-secondary'

app/views/comments/show.html.slim
p#notice = notice

p
  strong Username:
  = @comment.username
p
  strong Content:
  = @comment.content

  = link_to 'Edit', edit_blog_post_comment_path(@blog, @post, @comment), class: 'btn btn-primary'
  = link_to 'Back', [@blog, @post], class: 'btn btn-secondary'

app/views/layouts/application.html.slim
html
  head
    meta content="text/html; charset=UTF-8" http-equiv="Content-Type"
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
    meta http-equiv="x-ua-compatible" content="ie=edge"
    title Turbolinks Example
    = csrf_meta_tags
    = action_cable_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    = yield :head
  body[data-page="#{body_page_name}"]
    .container
      p#notice = notice
      = yield

app/views/posts/_form.html.slim
= form_for [@blog, @post] do |f|
  - if @post.errors.any?
    #error_explanation
      h2 = "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      ul
        - @post.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :username
    = f.text_field :username, class: 'form-control'
  .field
    = f.label :content
    = f.text_area :content, class: 'form-control'
  .actions = f.submit class: 'btn btn-primary'

app/views/posts/edit.html.slim
h1 Editing post

== render 'form'

= link_to 'Show', [@blog, @post], class: 'btn btn-secondary'
= link_to 'Back', @blog, class: 'btn btn-secondary'

app/views/posts/new.html.slim
h1 New post

== render 'form'

= link_to 'Back', @blog

app/views/posts/show.html.slim
h1
  ' Post by
  = @post.username
  ' in
  = @blog.title

.row
  .col-xs-12
    = @post.content

= link_to 'Edit', edit_blog_post_path(@blog, @post), class: 'btn btn-primary'
= link_to 'Back', @blog, class: 'btn btn-secondary'

h4 Comments

- @post.comments.each do |comment|
  .row
    .col-xs-12
      = comment.content
      ' by
      = comment.username
    .col-sm-6
      = link_to 'Show', [@blog, @post, comment], class: 'btn btn-secondary'
      = link_to 'Edit', edit_blog_post_comment_path(@blog, @post, comment), class: 'btn btn-secondary', data: {turbolinks_action: :replace}
      = link_to 'Destroy', [@blog, @post, comment], class: 'btn btn-secondary', data: { :confirm => 'Are you sure?' }, :method => :delete

= link_to 'New Comment', new_blog_post_comment_path(@blog, @post), class: 'btn btn-primary'